### ISSUE TITLE
ambiguous import

### ISSUE THREAD

**Issue by ldez** [TencentCloud/tencentcloud-sdk-go#172]
when `github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dnspod` is used as a transitive dependency an error occurs:

```console
$ go mod tidy
go: downloading github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.333
go: downloading github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dnspod v1.0.333
github.com/traefik/traefik/v2/pkg/provider/acme imports
        github.com/go-acme/lego/v4/providers/dns imports
        github.com/go-acme/lego/v4/providers/dns/tencentcloud imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common: ambiguous import: found package github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common in multiple modules:
        github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible/tencentcloud/common)
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.333 (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.333)
github.com/traefik/traefik/v2/pkg/provider/acme imports
        github.com/go-acme/lego/v4/providers/dns imports
        github.com/go-acme/lego/v4/providers/dns/tencentcloud imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile: ambiguous import: found package github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile in multiple modules:
        github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible/tencentcloud/common/profile)
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.333 (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.333/profile)
github.com/traefik/traefik/v2/pkg/provider/acme imports
        github.com/go-acme/lego/v4/providers/dns imports
        github.com/go-acme/lego/v4/providers/dns/tencentcloud imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dnspod/v20210323 imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors: ambiguous import: found package github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors in multiple modules:
        github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible/tencentcloud/common/errors)
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.333 (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.333/errors)
github.com/traefik/traefik/v2/pkg/provider/acme imports
        github.com/go-acme/lego/v4/providers/dns imports
        github.com/go-acme/lego/v4/providers/dns/tencentcloud imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dnspod/v20210323 imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http: ambiguous import: found package github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http in multiple modules:
        github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible/tencentcloud/common/http)
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.333 (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.333/http)
```

The error occurs because the `go.mod` file of all your modules doesn't declare the dependencies.

This happens for many of your modules.

Related to #171

**Comment by sesky4** [comment]
fixed

**Comment by ldez** [comment]
The problem is still here:
```console
$ go mod tidy
github.com/traefik/traefik/v2/pkg/provider/acme imports
        github.com/go-acme/lego/v4/providers/dns imports
        github.com/go-acme/lego/v4/providers/dns/tencentcloud imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common: ambiguous import: found package github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common in multiple modules:
        github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible/tencentcloud/common)
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.353 (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.353)
github.com/traefik/traefik/v2/pkg/provider/acme imports
        github.com/go-acme/lego/v4/providers/dns imports
        github.com/go-acme/lego/v4/providers/dns/tencentcloud imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile: ambiguous import: found package github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile in multiple modules:
        github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible/tencentcloud/common/profile)
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.353 (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.353/profile)
github.com/traefik/traefik/v2/pkg/provider/acme imports
        github.com/go-acme/lego/v4/providers/dns imports
        github.com/go-acme/lego/v4/providers/dns/tencentcloud imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dnspod/v20210323 imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors: ambiguous import: found package github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors in multiple modules:
        github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible/tencentcloud/common/errors)
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.353 (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.353/errors)
github.com/traefik/traefik/v2/pkg/provider/acme imports
        github.com/go-acme/lego/v4/providers/dns imports
        github.com/go-acme/lego/v4/providers/dns/tencentcloud imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/dnspod/v20210323 imports
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http: ambiguous import: found package github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http in multiple modules:
        github.com/tencentcloud/tencentcloud-sdk-go v3.0.83+incompatible (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v3.0.83+incompatible/tencentcloud/common/http)
        github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.353 (/home/ldez/sources/go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common@v1.0.353/http)
```

I think the problem is related to the fact that `github.com/tencentcloud/tencentcloud-sdk-go`  breaks the version continuity by moving from v3 to v1.

Maybe a solution can be to retract the old v3 modules:
- https://go.dev/blog/go116-module-changes#module-retraction
- https://go.dev/ref/mod#go-mod-file-retract
- https://pkg.go.dev/github.com/tencentcloud/tencentcloud-sdk-go?tab=versions
